### ISSUE TITLE
cannot use 'g' key when writing posts

### ISSUE THREAD

**Issue by aspiers** [mattburesh/bluesky-shortcuts#28]
Not sure if this was broken by #26 or something earlier, but if I try replying to a post now, the `g` key does nothing although all other keys work fine.  If I disable the extension the `g` key works perfectly again.

**Comment by mattburesh** [comment]
Shoot, I'm sure that's what did it. I'll get it fixed today. Thanks for point it out!

**Comment by mattburesh** [comment]
This should be fixed by #29 

Thanks for sending this in, I appreciate it. New build should be live in Firefox now, imagine Chrome will follow later today. 

Time for me to write some tests 😅

**Comment by aspiers** [comment]
Seems fixed now, thanks so much!!
